version: '3'

services:
  xvfb:
    image: xvfb
    command:
      ["remote"]

  robotframework:
    #build: .
    image: robot_framework
    depends_on:
    - xvfb
    volumes:
    #- ./test-suite:/test-suite
    - ./test-suite:/test-suite
    - ./report:/report
    command:
      [" --loglevel DEBUG -l log_results.html --outputdir /report /test-suite"]
      #[" --loglevel DEBUG test-suite/"]

    privileged: true
    #command:
    #  [" --help"]

volumes:
  report:
  test-suite: