version: '3'

services:
  xvfb:
    image: xvfb
    command:
      ["remote"]

  robotframework:
    #build: .
    image: robot_framework
    depends_on:
    - xvfb
    volumes:
    #- ${WORKSPACE}/test-suite:/test-suite
    #- ${WORKSPACE}/report:/report
    - ${PWD}/test-suite:/test-suite
    - ${PWD}/report:/report
    command:
      [" --loglevel DEBUG -l log_results.html --outputdir report /test-suite"]
      #[" --loglevel DEBUG /test-suite"]

    privileged: true
    #command:
    #  [" --help"]

volumes:
  test-suite:
  report: