version: '2'

services:
  xvfb:
    image: xvfb
    command:
      ["remote"]

  robotframework:
    #build: .
    image: robotframework
    depends_on:
    - xvfb
    volumes:
    #- ${WORKSPACE}/test-suite:/test-suite
    #- ${WORKSPACE}/report:/report
    #- ${PWD}/Suite:/Suite
    - ./report:/report
    command:
      [" --loglevel DEBUG -l log_results.html --outputdir report /test-suite"]
      #[" --loglevel DEBUG -l log_results.html --outputdir report Suite"]

      #[" --loglevel DEBUG /test-suite"]

    privileged: true
    #command:
    #  [" --help"]

volumes:
  report:
  #Suite: